export const ADD_USER_SCENE_ID = 'ADD_USER_SCENE_ID';
export const ADD_USER_WIZARD_ID = 'ADD_USER_WIZARD_ID';
export const ADD_ORDER_SCENE_ID = 'ADD_ORDER_SCENE_ID';
export const ADD_ORDER_WIZARD_ID = 'ADD_ORDER_WIZARD_ID';
