export enum WIZARDS {
  ADD_USER_WIZARD_ID = 'ADD_USER_WIZARD_ID',
  ADD_ORDER_WIZARD_ID = 'ADD_ORDER_WIZARD_ID',
  ADD_STAND_WIZARD_ID = 'ADD_STAND_WIZARD_ID',
  ADD_PART_IN_WIZARD_ID = 'ADD_PART_IN_WIZARD_ID',
  ADD_WORK_IN_WIZARD_ID = 'ADD_WORK_IN_WIZARD_ID',
}
