export enum WIZARDS {
  CLIENT_ADD = 'CLIENT_ADD',
  CLIENT_UPDATE = 'CLIENT_UPDATE',
  ORDER_ADD = 'ORDER_ADD',
  ADD_STAND_ORDER = 'ADD_STAND_ORDER',
  ADD_STAND_PROD = 'ADD_STAND_PROD',
  ADD_PART_IN = 'ADD_PART_IN',
  ADD_PART_OUT = 'ADD_PART_OUT',
  ADD_TASK = 'ADD_TASK',
  ADD_WORK = 'ADD_WORK',
  ADD_MASTER = 'ADD_MASTER',
  ADD_COMPONENT = 'ADD_COMPONENT',
  ADD_MONEY = 'ADD_MONEY',
}

export enum SCENES {
  ENTERING = 'ENTERING',
}
