export enum WIZARDS {
  ADD_CLIENT = 'ADD_CLIENT',
  ADD_ORDER = 'ADD_ORDER',
  ADD_STAND_ORDER = 'ADD_STAND_ORDER',
  ADD_STAND_PROD = 'ADD_STAND_PROD',
  ADD_PART_IN = 'ADD_PART_IN',
  ADD_PART_OUT = 'ADD_PART_OUT',
  ADD_TASK = 'ADD_TASK',
  ADD_WORK = 'ADD_WORK',
  ADD_MASTER = 'ADD_MASTER',
  ADD_COMPONENT = 'ADD_COMPONENT',
  ADD_FINANCIAL_TRANSACTION = 'ADD_FINANCIAL_TRANSACTION',
}

export enum SCENES {
  ENTERING = 'ENTERING',
}
